

server.servlet.context-path=/api/v1.5

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#uri for mongodb atlas
#spring.data.mongodb.uri=mongodb+srv://sounodip573_db_user:GkdwzUQE7Kg8q3FK@cluster0.hn1tyzm.mongodb.net/cloudshare
spring.data.mongodb.uri=mongodb://localhost:27017/cloudsharealt
frontend.url=http://localhost:5173
clerk.issuer= https://sterling-termite-65.clerk.accounts.dev
clerk.jwks-url= https://sterling-termite-65.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret = T2WFcX6V2FSQmpgYnbmDEDWra6ukFoca

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# Cloudflare R2 Configuration
r2.endpoint=https://3d0671fae8f5f480d7768b4003342071.r2.cloudflarestorage.com
r2.access-key-id=bfe249dcffd221913b77715f6d7c7171
r2.secret-access-key=331f6832975742bd8e5d3254a52f1c35f9a354f63549f91110aaf4c18bc2d5bb
r2.bucket-name=sharevault
r2.account-id=3d0671fae8f5f480d7768b4003342071

# RazorPay API Keys

razorpay.key.id = rzp_test_SaefaPlWTepEWc
razorpay.key.secret = wUYYavYA7RJrHW9J2OUmwoGu


